# Generated by Django 5.0 on 2023-12-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_partners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Projects',
        ),
    ]
