# Generated by Django 5.0 on 2023-12-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_rename_partners_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='url',
        ),
    ]
