# Generated by Django 5.0 on 2023-12-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_remove_projects_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
