# Generated by Django 5.0 on 2023-12-22 09:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_main_mainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст')),
            ],
            options={
                'verbose_name': 'Примущество2',
                'verbose_name_plural': 'Примущества2',
            },
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(upload_to='main_photo', verbose_name='Фотография'),
        ),
        migrations.CreateModel(
            name='MainImage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main2_photo', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Навзание')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main2_image', to='secondary.main2')),
            ],
            options={
                'unique_together': {('place_info', 'image')},
            },
        ),
    ]
