# Generated by Django 5.0 on 2023-12-22 10:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_main2_alter_mainimage_image_mainimage2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Окружение',
                'verbose_name_plural': 'Окружении',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номер школы')),
                ('time', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Время')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_univers', to='secondary.environment')),
            ],
            options={
                'unique_together': {('place_info', 'name')},
            },
        ),
    ]
