# Generated by Django 5.0 on 2023-12-22 10:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0012_environment_environmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='environmentimage',
            name='time',
            field=models.CharField(default=1, max_length=255, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
