# Generated by Django 5.0 on 2023-12-23 15:40

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0014_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Гордость',
                'verbose_name_plural': 'Гордости',
            },
        ),
        migrations.CreateModel(
            name='ReachText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Короткое описание')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='secondary.reach')),
            ],
            options={
                'unique_together': {('place_info', 'text')},
            },
        ),
    ]
