# Generated by Django 5.0 on 2023-12-23 15:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0015_reach_reachtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reach',
            name='name',
            field=ckeditor.fields.RichTextField(verbose_name='Название'),
        ),
    ]
