# Generated by Django 5.0 on 2023-12-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0017_alter_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название квартиры')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='ApartmentPluse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=255, verbose_name='Название комнаты')),
                ('meters', models.CharField(max_length=255, verbose_name='Площадь комнаты')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='secondary.apartment')),
            ],
            options={
                'unique_together': {('place_info', 'rooms')},
            },
        ),
    ]
