# Generated by Django 5.0 on 2023-12-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0018_apartment_apartmentpluse'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default=1, upload_to='image_apartment', verbose_name='Фото_комнаты'),
            preserve_default=False,
        ),
    ]
