# Generated by Django 5.0 on 2023-12-21 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_about'),
        ('secondary', '0007_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Места в комплексе')),
                ('kvartal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_kvartal', to='secondary.kvartal')),
            ],
            options={
                'unique_together': {('kvartal', 'place')},
            },
        ),
    ]
